name: workshop_dkmp

channels:
- conda-forge
- anaconda 

dependencies:
# Essential
- python==3.7.6
- nb_conda_kernels==2.2.0
- pip==19.3.1
- ipython==7.1.1
- tqdm==4.41.1
# Data Science
- numpy==1.18.1
- scipy==1.3.1
- pandas==0.25.3
# Machine Learning
- scikit-learn==0.22
- statsmodels==0.11.1
- scikit-surprise==1.0.6
# Visualization
- matplotlib==3.1.2
- seaborn==0.9.0
- ipywidgets==7.4.2
# NLP
- nltk==3.4.1
# Computer Vision
- pillow==5.4.1
# Clustering
- pyclustering==0.9.3.1

- pip:
  # Machine Learning
  - xgboost==0.80
  - scikit-optimize==0.7.4
  - jcopml==1.1.10
  - luwiji==1.1.8
  # Clustering
  - kmodes==0.10.2
